### ISSUE TITLE
xfce-base/libxfce4ui-4.16.0

### ISSUE THREAD

**Issue by jeandestouches** [Xfce-Classic/gentoo-overlay#1]
Hello,
Now xfce-4.16.x is stable, is this overlay going to be updated to track the stable release ?
Thank you very much!

**Comment by shawnanastasio** [comment]
Hi, thanks for the reminder. Bumped the ebuild to 4.16.0 with https://github.com/Xfce-Classic/gentoo-overlay/commit/899503e2702aa78e7d90acbd5f6b37fefcb7c510.

**Comment by jeandestouches** [comment]
Thanks, it works perfectly ! Cheers
